# [font.bold]
# family = "MonaspiceNe Nerd Font Mono"
# style = "Bold"

# [font.bold_italic]
# family = "MonaspiceNe Nerd Font Mono"
# style = "Bold Italic"

# [font.italic]
# family = "MonaspiceNe Nerd Font Mono"
# style = "Italic"

[font.normal]
family = "MonaspiceNe Nerd Font"
# style = "Regular"

[font]
size = 16

[window]
decorations = "None"
option_as_alt = "OnlyLeft"
